workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'

default:
  image: python:3.9
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh

  deploy:
    script:
      - flyctl deploy