stages:
  - deploy

deploy-job:
  stage: deploy
  image: python:3.9
  before_script:
    - apt-get update -qq && apt-get install -y curl
    - curl -L https://fly.io/install.sh | sh
  script:
    - /root/.fly/bin/flyctl deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'