stages:
  - build and deploy

deploy-job:
  stage: build and deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    FLY_ACCESS_TOKEN: $FLY_ACCESS_TOKEN
    FLY_APP_NAME: $FLY_APP_NAME
    DOCKER_IMAGE: registry.fly.io/$FLY_APP_NAME:$CI_COMMIT_SHORT_SHA
  before_script:
    - apk add curl
    - curl -L https://fly.io/install.sh | sh
    - /root/.fly/bin/flyctl auth docker
  script:
    - docker build -t "$DOCKER_IMAGE" .
    - /root/.fly/bin/flyctl deploy -i "$DOCKER_IMAGE"
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
