version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "27899:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  app:
    image: .
    container_name: app-node
    ports:
      - "27900:8080"
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    env_file:
      - .env
    environment:
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID:-DUMMYACCESSKEYID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY:-DUMMAYSECRETACCESSKEY}'
      REGION: '${AWS_REGION:-eu-west-1}'