from os import environ

DB_BASE_URL = environ["DB_BASE_URL"]
API_KEY = environ["API_KEY"]
APP_PWD = environ["APP_PWD"]
APP_SECRET_KEY = environ["APP_SECRET_KEY"]
GOOGLE_CLOUD_PROJECT = environ["GOOGLE_CLOUD_PROJECT"]
GOOGLE_APPLICATION_CREDENTIALS = environ["GOOGLE_APPLICATION_CREDENTIALS"]
